# Generated by Django 4.0 on 2021-12-19 15:02

from django.db import migrations, models
import django.db.models.deletion
import enigma.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnigmaRotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('sequence', models.CharField(max_length=26, validators=[enigma.validators.validate_iunique_word, enigma.validators.validate_iincludes_only_letters, enigma.validators.validate_has_twenty_six_characters])),
            ],
        ),
        migrations.CreateModel(
            name='EnigmaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnigmaSettingRotorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('rotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigma.enigmarotor')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigma.enigmasetting')),
            ],
            options={
                'unique_together': {('setting', 'rotor'), ('setting', 'order')},
                'index_together': {('setting', 'order')},
            },
        ),
        migrations.AddField(
            model_name='enigmasetting',
            name='rotors',
            field=models.ManyToManyField(related_name='+', through='enigma.EnigmaSettingRotorOrder', to='enigma.EnigmaRotor'),
        ),
        migrations.CreateModel(
            name='EnigmaPlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitution', models.CharField(max_length=2, validators=[enigma.validators.validate_iunique_word, enigma.validators.validate_iincludes_only_letters, enigma.validators.validate_has_two_characters])),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigma.enigmasetting')),
            ],
        ),
    ]
