# Generated by Django 4.0 on 2021-12-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigmaplug',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugs', to='enigma.enigmasetting'),
        ),
    ]
