# Generated by Django 4.0 on 2021-12-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0003_rename_enigmaplug_enigmaplugsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigmaplugsetting',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enigma.enigmasetting'),
        ),
    ]
