# Generated by Django 4.0 on 2021-12-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0004_alter_enigmaplugsetting_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigmasetting',
            name='indicator',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enigmaplugsetting',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plug_settings_set', to='enigma.enigmasetting'),
        ),
    ]
