# Generated by Django 4.0 on 2021-12-20 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0006_enigmasetting_reflector'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnigmaRotorNotch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notch', models.CharField(max_length=1)),
                ('rotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notch_set', to='enigma.enigmarotor')),
            ],
            options={
                'verbose_name': 'rotor notch',
                'verbose_name_plural': 'rotor notches',
                'ordering': ['rotor', 'notch'],
            },
        ),
    ]
