# Generated by Django 4.0 on 2021-12-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0007_enigmarotornotch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enigmasetting',
            name='indicator',
        ),
    ]
