# Generated by Django 4.0 on 2021-12-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0008_remove_enigmasetting_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='enigmasetting',
            name='indicator',
            field=models.CharField(default='AAA', max_length=3),
            preserve_default=False,
        ),
    ]
