# Generated by Django 4.0 on 2021-12-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enigma', '0009_enigmasetting_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enigmasetting',
            name='indicator',
            field=models.CharField(max_length=255),
        ),
    ]
